/**
 * W3C Design Token Community Group format.
 *
 * This is the universal escape hatch — anyone on Tailwind v3, on another
 * framework, or on no framework at all can consume this. It is the reason the
 * export surface does not need a generator per Tailwind version.
 */
import { RAMP_STOPS } from '../color';
import type { DesignTokens } from '../tokens';

type TokenNode = { $value: string; $type: string } | { [k: string]: TokenNode };

export function generateDtcg(t: DesignTokens): string {
  const color = (v: string) => ({ $value: v, $type: 'color' });
  const dim = (v: string) => ({ $value: v, $type: 'dimension' });

  const ramp = (name: 'brand' | 'neutral') =>
    Object.fromEntries(RAMP_STOPS.map((s) => [s, color(t.color[name][s])]));

  const doc: Record<string, TokenNode> = {
    color: {
      brand: ramp('brand'),
      neutral: ramp('neutral'),
      light: Object.fromEntries(Object.entries(t.color.light).map(([k, v]) => [k, color(v)])),
      dark: Object.fromEntries(Object.entries(t.color.dark).map(([k, v]) => [k, color(v)])),
    },
    spacing: Object.fromEntries(Object.entries(t.spacing).map(([k, v]) => [k, dim(v)])),
    radius: Object.fromEntries(Object.entries(t.radius).map(([k, v]) => [k, dim(v)])),
    fontSize: Object.fromEntries(Object.entries(t.type.scale).map(([k, v]) => [k, dim(v)])),
    fontFamily: {
      heading: { $value: t.type.heading, $type: 'fontFamily' },
      body: { $value: t.type.body, $type: 'fontFamily' },
      mono: { $value: t.type.mono, $type: 'fontFamily' },
    },
    shadow: Object.fromEntries(
      Object.entries(t.shadow).map(([k, v]) => [k, { $value: v, $type: 'shadow' }]),
    ),
  };

  return JSON.stringify({ $description: 'Generated by no-thoughts-just-swipe', ...doc }, null, 2);
}
