import type { DesignTokens } from '../tokens';
import type { DesignParams } from '../params';
import { AXES } from '../params';

export function generateReadme(t: DesignTokens, p: DesignParams, shareUrl?: string): string {
  const summary = AXES.map((a) => {
    const value = p[a.key];
    return `| ${a.label} | ${a.describe(value as never)} |`;
  }).join('\n');

  return `# Your design system

Generated by [no thoughts, just swipe](https://github.com/).

## Install

1. Copy \`app.css\` into your project and import it in your entry file:

   \`\`\`ts
   import './app.css';
   \`\`\`

2. Make sure Tailwind v4 is set up:

   \`\`\`bash
   npm i -D tailwindcss @tailwindcss/vite
   \`\`\`

3. Copy the \`components/\` folder wherever your UI lives.

> Built for **Tailwind v4**. On v3, or not using Tailwind at all? Use
> \`tokens.json\` — it is standard W3C DTCG format and converts cleanly.

## Choices

| Axis | Value |
| --- | --- |
${summary}

## Accessibility

Contrast was verified during generation:

- Body text on background: **${t.audit.textOnBg}:1** ${t.audit.textOnBg >= 4.5 ? '(AA)' : '(below AA)'}
- Accent on surface: **${t.audit.accentOnSurface}:1**
- Accent foreground on accent: **${t.audit.accentFgOnAccent}:1**

## Files

| File | What it is |
| --- | --- |
| \`app.css\` | Tailwind v4 \`@theme\` block — the source of truth |
| \`tokens.json\` | Same tokens in W3C DTCG format |
| \`components/\` | Button, Card, Input, Badge |
${shareUrl ? `\n## Regenerate\n\n${shareUrl}\n` : ''}`;
}
