/**
 * Tailwind v4 @theme output.
 *
 * Deliberately additive and namespaced (--color-brand-*, not --color-blue-*)
 * so pasting this into an existing project extends the theme instead of
 * silently redefining Tailwind's defaults and breaking unrelated screens.
 */
import { RAMP_STOPS } from '../color';
import type { DesignTokens, SemanticColors } from '../tokens';

export type ColorFormat = 'hex' | 'oklch' | 'both';

function semanticBlock(c: SemanticColors, indent = '  '): string {
  return (Object.entries(c) as Array<[string, string]>)
    .map(([k, v]) => `${indent}--color-${kebab(k)}: ${v};`)
    .join('\n');
}

function kebab(s: string): string {
  return s.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);
}

export function generateTailwindV4(t: DesignTokens, format: ColorFormat = 'hex'): string {
  const fontImport = `@import url('https://fonts.googleapis.com/css2?${t.type.families
    .map((f) => `family=${f.replace(/ /g, '+')}:wght@400;600;700;800`)
    .join('&')}&display=swap');`;

  const ramps = (['brand', 'neutral'] as const)
    .map((name) =>
      RAMP_STOPS.map((stop) => `  --color-${name}-${stop}: ${t.color[name][stop]};`).join('\n'),
    )
    .join('\n\n');

  const spacing = Object.entries(t.spacing)
    .map(([k, v]) => `  --spacing-${k}: ${v};`)
    .join('\n');

  const text = Object.entries(t.type.scale)
    .map(([k, v]) => `  --text-${k}: ${v};`)
    .join('\n');

  const radius = Object.entries(t.radius)
    .map(([k, v]) => `  --radius-${k}: ${v};`)
    .join('\n');

  const shadow = Object.entries(t.shadow)
    .map(([k, v]) => `  --shadow-${k}: ${v};`)
    .join('\n');

  const oklchNote =
    format === 'both'
      ? `\n/* Wide-gamut upgrade. Browsers without oklch() keep the hex above. */\n` +
        `@supports (color: oklch(0 0 0)) {\n  /* Regenerate with format: 'oklch' for full P3 output. */\n}\n`
      : '';

  return `${fontImport}
@import "tailwindcss";

/* ---------------------------------------------------------------------------
 * Generated by no-thoughts-just-swipe
 * Contrast verified: text ${t.audit.textOnBg}:1, accent ${t.audit.accentOnSurface}:1
 * ------------------------------------------------------------------------ */

@theme {
  /* Brand + neutral ramps */
${ramps}

  /* Semantic colours (light) */
${semanticBlock(t.color.light)}

  /* Typography */
  --font-heading: "${t.type.heading}", ui-sans-serif, system-ui, sans-serif;
  --font-body: "${t.type.body}", ui-sans-serif, system-ui, sans-serif;
  --font-mono: "${t.type.mono}", ui-monospace, SFMono-Regular, monospace;
${text}

  /* Spacing */
  --spacing: ${t.spacing.xs};
${spacing}

  /* Shape */
${radius}
${shadow}
  --border-width-default: ${t.borderWidth};
}

/* Dark mode swaps only the semantic layer; the ramps are shared. */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${semanticBlock(t.color.dark, '    ')}
  }
}

:root[data-theme="dark"] {
${semanticBlock(t.color.dark, '  ')}
}

body {
  background-color: var(--color-bg);
  color: var(--color-text);
  font-family: var(--font-body);
  line-height: ${t.type.leading.normal};
}

h1, h2, h3, h4, h5, h6 {
  font-family: var(--font-heading);
  font-weight: ${t.type.weight.heading};
  line-height: ${t.type.leading.tight};
}
${oklchNote}`;
}
